# Generated by Django 5.1.4 on 2025-02-21 19:47

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usercustomer_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustomer",
            name="username",
            field=models.CharField(
                default=12,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
            preserve_default=False,
        ),
    ]
