# Generated by Django 5.1.4 on 2025-02-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usercustomer_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercustomer",
            name="username",
        ),
    ]
