# Generated by Django 5.1.4 on 2025-02-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_usercustomer_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usercustomer",
            managers=[],
        ),
    ]
