# Generated by Django 5.1.4 on 2025-02-22 11:33

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_usercustomer_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usercustomer",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
