# Generated by Django 5.1.4 on 2025-02-22 16:02

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_usercustomer_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usercustomer",
            managers=[],
        ),
        migrations.AlterField(
            model_name="usercustomer",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите аватар",
                null=True,
                upload_to="user_avatar",
                verbose_name="Аватар:",
            ),
        ),
        migrations.AlterField(
            model_name="usercustomer",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Укажите страну",
                max_length=50,
                null=True,
                verbose_name="Страна проживания:",
            ),
        ),
        migrations.AlterField(
            model_name="usercustomer",
            name="email",
            field=models.EmailField(
                help_text="Введите email",
                max_length=254,
                unique=True,
                verbose_name="Почта (username):",
            ),
        ),
        migrations.AlterField(
            model_name="usercustomer",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="Введите имя", max_length=30, verbose_name="Имя:"
            ),
        ),
        migrations.AlterField(
            model_name="usercustomer",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Введите фамилию",
                max_length=30,
                verbose_name="Фамилия:",
            ),
        ),
        migrations.AlterField(
            model_name="usercustomer",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Введите телефон",
                max_length=128,
                null=True,
                region=None,
                verbose_name="Телефон:",
            ),
        ),
    ]
