# Generated by Django 5.1.4 on 2025-01-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(help_text='Введите заголовок статьи', max_length=100, unique=True, verbose_name='Заголовок статьи')),
                ('article_contents', models.TextField(help_text='Введите содержимое статьи', verbose_name='Содержимое статьи')),
                ('image', models.ImageField(blank=True, help_text='Добавьте превью', upload_to='article_image/', verbose_name='Превью (изображение)')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, help_text='Зафиксируйте факт публикации', verbose_name='Признак публикации')),
                ('views_counter', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'blog_articles',
                'ordering': ['article_title'],
            },
        ),
    ]
