# Generated by Django 5.1.4 on 2025-01-26 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contactsdata_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsdata',
            name='address',
            field=models.TextField(help_text='Введите юридический адрес магазина', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactsdata',
            name='country',
            field=models.CharField(help_text='Введите страну регистрации магазина', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='contactsdata',
            name='tax_id',
            field=models.CharField(help_text='Введите ИНН магазина', max_length=20, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='Укажите цену товара', verbose_name='Цена товара'),
        ),
    ]
