# Generated by Django 5.1.4 on 2025-01-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_contactsdata_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('phone', models.IntegerField(max_length=15, verbose_name='Телефон пользователя')),
                ('message', models.TextField(verbose_name='Сообщение от пользователя')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'catalog_feedback',
                'ordering': ['phone'],
            },
        ),
    ]
