# Generated by Django 5.1.4 on 2025-02-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_feedback_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product_name"],
                "permissions": [("can_unpublish_product", "Может отменять публикацию")],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Зафиксируйте факт публикации",
                verbose_name="Признак публикации",
            ),
        ),
    ]
