# Generated by Django 5.1.4 on 2025-02-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options_product_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото товара",
                null=True,
                upload_to="product_image/",
                verbose_name="Фотография товара",
            ),
        ),
    ]
