# Generated by Django 5.1.4 on 2025-02-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Зафиксируйте факт публикации",
                verbose_name="Признак публикации",
            ),
        ),
    ]
