# Generated by Django 5.1.4 on 2025-02-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product_name"],
                "permissions": [
                    (
                        "can_change_product_publication",
                        "Может управлять публикацией продукта (опубликовать / отменить)",
                    )
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
